Update CI scripts

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,3 +1,7 @@
 #!/bin/bash
 
+set -eu
+
+echo "No external dependencies currently required."
+
 exit
